-- Raajwarasa schema — PostgreSQL 16
-- Managed by Flyway. Never edit an applied migration; add V2__, V3__, ...

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_categories_slug UNIQUE (slug)
);

CREATE TABLE artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    category_id BIGINT NOT NULL,
    description VARCHAR(1000),
    historical_context TEXT,
    craftsmanship TEXT,
    material VARCHAR(150),
    period VARCHAR(150),
    origin VARCHAR(150),
    region VARCHAR(250),
    size VARCHAR(200),
    "condition" VARCHAR(250),
    preservation VARCHAR(1000),
    provenance VARCHAR(500),
    availability VARCHAR(50) DEFAULT 'ON_REQUEST',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_artifacts_slug UNIQUE (slug),
    CONSTRAINT fk_artifacts_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_artifacts_category ON artifacts (category_id);
CREATE INDEX idx_artifacts_active ON artifacts (active);
CREATE INDEX idx_artifacts_featured ON artifacts (featured);

CREATE TABLE artifact_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT,
    url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(300),
    sort_order INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_artifact_images_artifact FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE
);

CREATE INDEX idx_artifact_images_artifact ON artifact_images (artifact_id);

CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    display_name VARCHAR(150),
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_ADMIN',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_admin_users_username UNIQUE (username)
);

CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL,
    phone VARCHAR(40),
    city VARCHAR(120),
    artifact_id BIGINT,
    artifact_name VARCHAR(220),
    message TEXT,
    source VARCHAR(50),
    preferred_contact VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    admin_notes TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_inquiries_status ON inquiries (status);
CREATE INDEX idx_inquiries_created ON inquiries (created_at);

CREATE TABLE inquiry_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT,
    note TEXT NOT NULL,
    created_by VARCHAR(150),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_inquiry_notes_inquiry FOREIGN KEY (inquiry_id) REFERENCES inquiries (id) ON DELETE CASCADE
);

CREATE INDEX idx_inquiry_notes_inquiry ON inquiry_notes (inquiry_id);

CREATE TABLE journal_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    slug VARCHAR(260) NOT NULL,
    category VARCHAR(120),
    content TEXT,
    cover_image VARCHAR(500),
    author VARCHAR(150),
    publish_date TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    seo_title VARCHAR(200),
    seo_description VARCHAR(500),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_journal_slug UNIQUE (slug)
);

CREATE INDEX idx_journal_status ON journal_articles (status);

CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(300),
    url VARCHAR(600) NOT NULL,
    mime_type VARCHAR(50),
    kind VARCHAR(20) DEFAULT 'image',
    alt_text VARCHAR(300),
    artifact_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_media_artifact FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE
);

CREATE INDEX idx_media_artifact ON media (artifact_id);