-- Raajwarasa sales: artifact pricing + customer orders.
-- Migration runs once via Flyway.

ALTER TABLE artifacts ADD COLUMN price NUMERIC(12,2);
ALTER TABLE artifacts ADD COLUMN sale_available BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE artifacts SET price = 48500.00, sale_available = TRUE
WHERE slug = 'maratha-pattern-bronze-kavacha-vessel';

UPDATE artifacts SET price = 26500.00, sale_available = TRUE
WHERE slug = 'iron-tulwar-with-bronze-overlay';

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(120) NOT NULL,
    state VARCHAR(120) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    delivery_mode VARCHAR(30) NOT NULL DEFAULT 'STANDARD',
    payment_method VARCHAR(30) NOT NULL DEFAULT 'COD',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    total_amount NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_orders_order_number UNIQUE (order_number)
);

CREATE INDEX idx_orders_created ON orders (created_at);
CREATE INDEX idx_orders_status ON orders (status);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    artifact_id BIGINT,
    artifact_name VARCHAR(220) NOT NULL,
    artifact_url VARCHAR(600),
    unit_price NUMERIC(12,2) NOT NULL,
    quantity INTEGER NOT NULL,
    line_total NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_artifact FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE SET NULL
);

CREATE INDEX idx_order_items_order ON order_items (order_id);