ALTER TABLE orders ALTER COLUMN address DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN city DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN state DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN pincode DROP NOT NULL;